version: 2

jobs:
  build:
    docker:
      - image: rust:1-buster
    steps:
      - checkout
      - run:
          name: Install libclang
          command: |
            gcc --version
            g++ --version
            apt-get -y update
            apt-get -y install libclang-dev clang libclang-7-dev libgcc-8-dev libclang-common-7-dev cmake
            # Make clang the default compiler (needed for binaryen, wabt and others with native bindings)
            update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
            update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
            gcc --version
            g++ --version
      - run:
          name: Update rustc
          command: |
            rustup component add rustfmt
            rustup update
            cargo --version
            rustc --version
      - run:
           name: Check formatting
           command: |
             rustfmt --version
             cargo fmt --all -- --check
      - run:
          name: Build
          command: |
             cargo build --release
             # Explicitly move into the libchisel directory to properly build with features
             # FIXME: make this work in workspace
             cd libchisel && cargo build --release --features binaryen && cd ..
      - run:
          name: Test
          command: |
             cargo test
             # Explicitly move into the libchisel directory to properly build with features
             # FIXME: make this work in workspace
             cd libchisel && cargo test --features binaryen && cd ..
